# Generated by Django 3.1.7 on 2021-03-27 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attach',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='添付ファイル'),
        ),
    ]
